### ISSUE TITLE
Getting - Unhandled 'error' event on running given sample example.

### ISSUE THREAD

**Issue by prashantkoshta** [bahamas10/node-curl-cmd#1]
After running given example, I am getting following error.

=> curl -X GET 'http://www.daveeddy.com:80/something'

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete](net.js:895:19)

**Comment by bahamas10** [comment]
Can you show me what you are running to get this error? I can't reproduce it
